name: Build and deploy Next.js app to Azure Web App - test-next

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install and build
        run: |
          npm install
          npm run build
        # Note: You may have to adjust the build command to match your Next.js project setup

      # Optionally, you can run tests before deployment
      - name: npm test
        run: |
          npm test
        # Adjust this command to run your tests as needed

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: next-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: next-app

      - name: Install pm2 (optional, for running Next.js in production)
        run: |
          npm install pm2 -g

      - name: Start Next.js app with SSR using pm2
        run: |
          npm install
          pm2 start npm --name "next-app" -- start

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'test-next'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9AAD87DF2D3E49B287C49CCD2C628616 }}
          package: .
